In [1]:
from sklearn.decomposition import PCA
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler

In [2]:
import pandas as pd
import numpy as np
import pickle

In [3]:
pca = PCA(n_components=3)
lr = LinearRegression()
ss = StandardScaler()

In [4]:
data2 = pd.DataFrame([[1,2,3,4,9],[5,6,7,8,9]])
data2

0  1  2  3  4
0  1  2  3  4  9
1  5  6  7  8  9

In [5]:
data = pd.DataFrame([[1,2,3,4,9],[5,6,7,8,9]])
data = data.sample(20, replace=True)
data

0  1  2  3  4
1  5  6  7  8  9
1  5  6  7  8  9
0  1  2  3  4  9
0  1  2  3  4  9
1  5  6  7  8  9
1  5  6  7  8  9
1  5  6  7  8  9
0  1  2  3  4  9
0  1  2  3  4  9
0  1  2  3  4  9
1  5  6  7  8  9
1  5  6  7  8  9
1  5  6  7  8  9
1  5  6  7  8  9
0  1  2  3  4  9
1  5  6  7  8  9
0  1  2  3  4  9
1  5  6  7  8  9
0  1  2  3  4  9
1  5  6  7  8  9

In [6]:
data = ss.fit_transform(data)
data = pca.fit_transform(data)
data

/usr/local/lib/python3.7/site-packages/sklearn/preprocessing/data.py:617: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
/usr/local/lib/python3.7/site-packages/sklearn/base.py:462: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)


array([[-1.63299316e+00,  1.70934989e-15,  1.17224617e-17],
       [-1.63299316e+00, -7.87275889e-17, -8.93866141e-19],
       [ 2.44948974e+00,  9.35950321e-17, -2.01491118e-17],
       [ 2.44948974e+00,  9.35950321e-17, -2.01491118e-17],
       [-1.63299316e+00, -7.87275889e-17, -8.93866141e-19],
       [-1.63299316e+00, -7.87275889e-17, -8.93866141e-19],
       [-1.63299316e+00, -7.87275889e-17, -8.93866141e-19],
       [ 2.44948974e+00,  9.35950321e-17, -2.01491118e-17],
       [ 2.44948974e+00,  9.35950321e-17, -2.01491118e-17],
       [ 2.44948974e+00,  9.35950321e-17, -2.01491118e-17],
       [-1.63299316e+00, -7.87275889e-17, -8.93866141e-19],
       [-1.63299316e+00, -7.87275889e-17, -8.93866141e-19],
       [-1.63299316e+00, -7.87275889e-17, -8.93866141e-19],
       [-1.63299316e+00, -7.87275889e-17, -8.93866141e-19],
       [ 2.44948974e+00,  9.35950321e-17, -2.01491118e-17],
       [-1.63299316e+00, -7.87275889e-17, -8.93866141e-19],
       [ 2.44948974e+00, -3.53662766e-17

In [7]:
data2 = ss.transform(data2)
data2 = pca.transform(data2)
data2

/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:1: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  """Entry point for launching an IPython kernel.


array([[ 2.44948974e+00,  7.48468363e-16, -1.12272101e-17],
       [-1.63299316e+00, -4.75186866e-16, -1.50274135e-17]])

In [8]:
data = pd.DataFrame(data)
lr = lr.fit(data.iloc[:, :2], data.iloc[:, 2])

In [9]:
data2 = pd.DataFrame(data2)
lr.predict(data2.iloc[:, :2])

array([2.97660812e-18, 2.97660812e-18])

In [10]:
d = dict({'ss' : ss, 'pca' : pca, 'model' : lr})

In [11]:
f = open("pipeline.pkl", "wb")
pickle.dump(d, f)
f.close()

In [12]:
f2 = open("pipeline.pkl", "rb")
loaded_d = pickle.load(f2)
f2.close()
loaded_d

{'ss': StandardScaler(copy=True, with_mean=True, with_std=True),
 'pca': PCA(copy=True, iterated_power='auto', n_components=3, random_state=None,
   svd_solver='auto', tol=0.0, whiten=False),
 'model': LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
          normalize=False)}

In [14]:
ss1 = loaded_d['ss']
pca1 = loaded_d['pca']
model = loaded_d['model']

In [15]:
data2 = pd.DataFrame([[1,2,3,4,9],[5,6,7,8,9]])
data2
data2 = ss1.transform(data2)
data2 = pca1.transform(data2)
data2 = pd.DataFrame(data2)
model.predict(data2.iloc[:, :2])

/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:3: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  This is separate from the ipykernel package so we can avoid doing imports until


array([2.97660812e-18, 2.97660812e-18])